# Generated by Django 5.0.6 on 2024-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="resumes",
            field=models.ManyToManyField(related_name="jobs", to="resumes.resume"),
        ),
    ]
