# Generated by Django 5.0.6 on 2024-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_created_at_job_updated_at_alter_job_openings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
