# Generated by Django 5.0.6 on 2024-05-14 13:42

import django.core.validators
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(max_length=250, validators=[jobs.models.validate_taiwan_address]),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50, message='年資必須低於50')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
