# Generated by Django 5.0.6 on 2024-05-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_user_job_job_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_resume",
            name="status",
            field=models.CharField(default="applied", max_length=20),
        ),
        migrations.AddField(
            model_name="job_resume",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
