# Generated by Django 5.0.6 on 2024-05-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_job_resume_status_job_resume_withdrawn_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_resume",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
