# Generated by Django 5.0.6 on 2024-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_job_resume_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_resume",
            name="interview_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job_resume",
            name="interview_invitation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
