# Generated by Django 5.0.6 on 2024-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_job_resume_interview_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_resume",
            name="interview_invitation",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
