# Generated by Django 5.0.6 on 2024-05-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_alter_job_resume_interview_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_resume",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
