# Generated by Django 5.0.6 on 2024-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_job_resume_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_resume",
            name="accepted",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="job_resume",
            name="interview_invitation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
