# Generated by Django 5.0.6 on 2024-05-13 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="profile",
            new_name="resume",
        ),
    ]
