# Generated by Django 5.0.6 on 2024-05-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_posit"),
        ("resumes", "0006_alter_resume_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="resumes.resume",
            ),
        ),
    ]
