# Generated by Django 5.0.6 on 2024-06-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_posit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['posit']},
        ),
    ]
