# Generated by Django 5.0.6 on 2024-05-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="posit",
            field=models.IntegerField(default=0),
        ),
    ]
