# Generated by Django 5.0.4 on 2024-05-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0003_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.FileField(null=True, upload_to="img/"),
        ),
    ]
