# Generated by Django 5.0.6 on 2024-05-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_posit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
