# Generated by Django 5.0.4 on 2024-05-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_delete_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
