# Generated by Django 5.0.6 on 2024-05-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_resume_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
