# Generated by Django 5.0.6 on 2024-05-13 06:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0004_alter_profile_picture"),
        ("resumes", "0005_delete_project"),
    ]

    operations = []
