# Generated by Django 5.0.6 on 2024-05-13 10:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("educations", "0003_rename_profile_education_resume"),
        ("projects", "0002_rename_profile_project_resume"),
        ("resumes", "0006_merge_0004_alter_profile_picture_0005_delete_project"),
        ("works", "0002_rename_profile_work_resume"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Resume",
        ),
        migrations.RenameField(
            model_name="resume",
            old_name="profile_id",
            new_name="resume_id",
        ),
    ]
