# Generated by Django 5.0.6 on 2024-05-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0006_alter_resume_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="birthday",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
