# Generated by Django 5.0.6 on 2024-05-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0007_alter_resume_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
