# Generated by Django 5.0.6 on 2024-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_alter_resume_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='style',
            field=models.IntegerField(default=1),
        ),
    ]
