# Generated by Django 5.0.6 on 2024-06-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_resume_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
