# Generated by Django 5.0.6 on 2024-05-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_card_area_company_card_banner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='card_area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='card_banner',
            new_name='banner',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='card_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='card_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='card_type',
            new_name='type',
        ),
    ]
