# Generated by Django 5.0.6 on 2024-05-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_alter_company_tel"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
