# Generated by Django 5.0.6 on 2024-05-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_card_area_company_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
    ]
