# Generated by Django 5.0.6 on 2024-05-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_company_name_alter_company_tel_and_more'),
        ('companies', '0005_alter_company_tags'),
    ]

    operations = [
    ]
