# Generated by Django 5.0.6 on 2024-05-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_merge_20240522_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='area',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
    ]
