# Generated by Django 5.0.4 on 2024-05-06 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "男"), ("F", "女"), ("N", "不透露")], max_length=1
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1年以下", "一年以下"),
                            ("3年以下", "三年以下"),
                            ("3年以上", "三年以上"),
                            ("5年以上", "五年以上"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("skills", models.CharField(blank=True, max_length=200, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
