# Generated by Django 5.0.4 on 2024-05-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_education_project_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="picture",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
