# Generated by Django 5.0.4 on 2024-05-12 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education_project_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
