# Generated by Django 5.0.6 on 2024-05-13 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("educations", "0002_rename_educations_education"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="profile",
            new_name="resume",
        ),
    ]
