# Generated by Django 5.0.6 on 2024-05-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educations", "0003_education_posit"),
        ("resumes", "0006_alter_resume_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="resumes.resume",
            ),
        ),
    ]
