# Generated by Django 5.0.6 on 2024-05-27 15:05

import positions.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("educations", "0004_alter_education_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="posit",
            field=positions.fields.PositionField(default=-1),
        ),
    ]
