# Generated by Django 5.0.6 on 2024-05-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("educations", "0005_alter_education_posit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
