# Generated by Django 5.0.6 on 2024-05-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0006_alter_resume_picture"),
        ("works", "0002_work_posit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works",
                to="resumes.resume",
            ),
        ),
    ]
