# Generated by Django 5.0.6 on 2024-05-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0007_rename_profile_resume_and_more"),
        ("works", "0002_rename_profile_work_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="resumes.resume"
            ),
        ),
    ]
