# Generated by Django 5.0.6 on 2024-05-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("works", "0006_alter_work_end_date_alter_work_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="is_current",
            field=models.BooleanField(
                choices=[(True, "是"), (False, "否")], default=False
            ),
        ),
    ]
